apiVersion: v1
kind: Pod
metadata:
  name: aws-api
spec:
  containers:
    - name: aws-api
      image: 774429751797.dkr.ecr.us-west-2.amazonaws.com/aws-api:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  serviceAccountName: aws-api
  volumes:
    - name: vault-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 7200
              audience: vault
